---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 192.168.1.17
      ansible_user: maks
      ansible_password: 1
vector:
  hosts:
    vector:
      ansible_host: 192.168.1.17
      ansible_user: maks
      ansible_password: 1
